name: Build

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 0 */7 * *" # Every week
    
env:
  NODE_VERSION: 18.x

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Lint
        run: |
          yarn install
          yarn lint

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run conversion
        run: |
          yarn install
          yarn convert

      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.repository == 'AdguardTeam/companiesdb'
        run: |
          git config --global user.name 'GH action'
          git config --global user.email 'devteam@adguard.com'
          git add dist/*
          git commit -m "Auto-update"
          git push
