name: Build

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 0 */7 * *" # Every week

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Lint
        run: |
          yarn install
          yarn lint

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Fetch whotracks.me data
        run: |
          aws --no-sign-request s3 cp s3://data.whotracks.me/trackerdb.sql .
        env:
          AWS_DEFAULT_REGION: us-east-1

      - name: Run conversion
        run: |
          yarn install
          yarn convert

      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.repository == 'AdguardTeam/companiesdb'
        run: |
          git config --global user.name 'GH action'
          git config --global user.email 'devteam@adguard.com'
          git add dist/whotracksme.json dist/companies.json
          git commit -m "Auto-update"
          git push
